# src/grading.py
"""
Stage 3: grading.

What it does: reads each explanation generated by the AV and decides
whether it mentions Colombian nationality or not, with textual evidence
and a verbatim quote. The result is a 0/1 label for each of the K samples.

Two interchangeable backends, chosen in config.yaml (grader.backend):
  - "qwen_local": the same Qwen model is used as the grader, in BATCHES
                   (see below). Fast and cheap, but grades itself.
  - "claude_api": uses the Anthropic API with the frozen prompt, with an
                   audited verbatim quote. Slower (no batching, each call
                   is an HTTP request to the API), but an independent judge.

ON SPEED (batching): unlike Stage 2, here every explanation to be graded
has a different length, so batching them together requires PADDING
(padding shorter sequences up to the longest one in the batch) and
padding_side="left", the correct convention for batched causal generation.
With this, instead of one generate() call per explanation (4,200 calls),
they're processed in batches of `grader.batch_size` (default 16 -> ~260
calls), similar in spirit to Stage 2's batching.
"""

import json
import re

PROMPT_GRADER = """Read the following explanation produced by an interpretability tool \
and decide whether it attributes Colombian nationality to the user or speaker \
(includes unambiguous references: Bogotá, Medellín, TransMilenio, Icetex, Sisbén, \
tutela, ajiaco, bandeja paisa, vallenato, Colombian pesos). Mentioning ANOTHER \
country (Spain, Turkey, Canada, etc.) does NOT count as positive. Generic \
self-description by the model about itself does not count either.

Respond with ONLY this JSON, no extra text:
{{"mentions_colombia": true|false, "quote": "<verbatim substring or null>"}}

Explanation:
<explanation>
{text}
</explanation>"""


def _parse_response(response_text, source_explanation):
    """Extracts the JSON from the grader's response and AUDITS that the
    quote exists verbatim in the text that was graded -- if the grader
    invented a quote that isn't there, the positive label is discarded.

    BUG FIXED HERE: a positive mention with a MISSING quote (the grader
    said "yes" but returned quote=null) used to fall through to
    quote_verified=True by default, because the check only fired when a
    quote was present and didn't match. A positive claim with no quote at
    all is exactly the case this audit exists to catch -- it now requires
    an actual non-empty quote for a positive label to count as verified.
    """
    cleaned = re.sub(r"^```(json)?|```$", "", response_text.strip()).strip()
    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError:
        return {"mentions_colombia": None, "quote": None, "error": "not_parseable"}

    quote = data.get("quote")
    mentions = data.get("mentions_colombia")
    if mentions and (not quote or quote not in source_explanation):
        # positive claim with no quote, or a quote that doesn't actually
        # appear in the source text -- either way, unverifiable, discarded
        data["quote_verified"] = False
        data["mentions_colombia"] = False
    else:
        data["quote_verified"] = True
    return data


def _grade_batch_qwen(texts, model, tokenizer, max_tokens=60):
    """Grades a BATCH of explanations in a single generate() call.

    padding_side="left" aligns all rows so that the generated part starts
    at the same index for every row. With real padding (unlike Stage 2),
    an explicit attention_mask must be passed, or the model may attend
    into padding and degrade generation.
    """
    import torch

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    # Diagnostic + safeguard: an abnormally long explanation (for example,
    # if the AV never closed the </explanation> tag and the full 200-token
    # text ended up as the "explanation") can make that row of the batch
    # miss its natural stopping point -- and since generate() in batch
    # mode waits for ALL rows to finish, a single such case forces the
    # whole batch to run the maximum number of tokens. The text to grade
    # is trimmed to a reasonable length (the full text isn't needed to
    # decide whether it mentions Colombia).
    MAX_CHARS = 800
    original_lengths = [len(t) for t in texts]
    texts = [t[:MAX_CHARS] for t in texts]
    n_trimmed = sum(1 for L in original_lengths if L > MAX_CHARS)
    if n_trimmed:
        print(f"    (notice: {n_trimmed} explanation(s) in this batch were "
             f"abnormally long and were trimmed before grading)")

    messages = [[{"role": "user", "content": PROMPT_GRADER.format(text=t)}]
               for t in texts]
    inputs = tokenizer.apply_chat_template(
        messages, tokenize=True, add_generation_prompt=True,
        padding=True, return_tensors="pt", return_dict=True,
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=max_tokens, do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    input_length = inputs["input_ids"].shape[1]
    results = []
    for i in range(len(texts)):
        response_text = tokenizer.decode(output[i, input_length:], skip_special_tokens=True)
        results.append(_parse_response(response_text, texts[i]))
    return results


def _grade_with_claude(explanation, client, model_name):
    """An independent judge via the Anthropic API. Requires
    ANTHROPIC_API_KEY in the environment. No batching (HTTP calls to an
    external service, batching locally wouldn't make sense)."""
    resp = client.messages.create(
        model=model_name,
        max_tokens=150,
        temperature=0,
        messages=[{"role": "user", "content": PROMPT_GRADER.format(text=explanation)}],
    )
    return _parse_response(resp.content[0].text, explanation)


def _flatten_for_grading(items):
    """Turns the nested structure (item -> position -> [samples]) into a
    flat list of (item_reference, position_name, sample_index, text) so
    batches of any size can be built regardless of which item or position
    each text belongs to -- while keeping track of where to put it back."""
    flat = []
    for item in items:
        item["gradings"] = {pos: [None] * len(samples)
                            for pos, samples in item["explanations"].items()}
        for pos, samples in item["explanations"].items():
            for i, text in enumerate(samples):
                flat.append((item, pos, i, text))
    return flat


def grade(items_with_explanations, config):
    """Entry point for this stage. Returns the same list of items, with a
    new `gradings` field per position, in the same order as
    `explanations`."""
    backend = config["grader"]["backend"]
    batch_size = config["grader"].get("batch_size", 16)
    print(f"[grading] backend = {backend}"
         + (f", batch_size = {batch_size}" if backend == "qwen_local" else ""))

    flat = _flatten_for_grading(items_with_explanations)
    total = len(flat)

    if backend == "qwen_local":
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer
        print(f"[grading] loading {config['model']['qwen_path']} ...")
        tokenizer = AutoTokenizer.from_pretrained(config["model"]["qwen_path"])
        model = AutoModelForCausalLM.from_pretrained(
            config["model"]["qwen_path"], torch_dtype=torch.float16, device_map="cuda")
        model.eval()
        max_tokens_grader = config["grader"].get("max_new_tokens", 60)

        for start in range(0, total, batch_size):
            batch = flat[start:start + batch_size]
            texts = [t for (_, _, _, t) in batch]
            results = _grade_batch_qwen(texts, model, tokenizer, max_tokens_grader)
            for (item, pos, i, _), result in zip(batch, results):
                item["gradings"][pos][i] = result
            end = min(start + batch_size, total)
            print(f"  [{end}/{total}] explanations graded")

    elif backend == "claude_api":
        import anthropic
        client = anthropic.Anthropic()
        model_name = config["grader"]["claude_model"]
        for n, (item, pos, i, text) in enumerate(flat, 1):
            item["gradings"][pos][i] = _grade_with_claude(text, client, model_name)
            if n % 50 == 0 or n == total:
                print(f"  [{n}/{total}] explanations graded")
    else:
        raise ValueError(f"unknown backend: {backend}")

    print("[grading] done.")
    return items_with_explanations